### ISSUE TITLE
in file data_tools.py ,the function add_noise_to_wavfile have some error?

### ISSUE THREAD

**Issue by l2009312042** [ivallesp/Xception1d#1]
```
def add_noise_to_wavfile(wav, amplitude_factor, clip_to_original_range=False):
    max_wav = max(wav)
    min_wav = min(wav)
    noise = np.random.rand(*wav.shape) * (max_wav - min_wav) - min_wav
    wav = wav + amplitude_factor * noise
    if clip_to_original_range:
        wav = np.clip(wav, min_wav, max_wav)
    return wav
```

the calution of noise should be 
noise = np.random.rand(*wav.shape) * (max_wav - min_wav) + min_wav?

the range of  np.random.rand(*wav.shape)  is (0,1), the range of noise  is expected to be (min_wav,max_wav)?
so  the third term shoub be + min_wav?

**Comment by ivallesp** [comment]
That is correct, thanks for pointing it out. Feel free to send a pull
request and I will accept the change
